CREATE TABLE [dbo].[database_access_audit] (
    [DatabaseAccessAuditRecordId]                BIGINT           IDENTITY (1, 1) NOT NULL,
    [CreateDate]                                 DATETIME         CONSTRAINT [DF_database_access_audit_CreateDate] DEFAULT (getdate()) NOT NULL,
    [UpdateDate]                                 DATETIME         CONSTRAINT [DF_database_access_audit_UpdateDate] DEFAULT (getdate()) NOT NULL,
    [UserId]                                     [dbo].[dtUserId] CONSTRAINT [DF_database_access_audit_UserId] DEFAULT (replace(suser_sname(),'THOR\','')) NOT NULL,
    [Version]                                    BIGINT           NOT NULL,
    [VersionComment]                             VARCHAR (1000)   NULL,
    [LoginId]                                    VARCHAR (100)    NOT NULL,
    [DatabaseLoginName]                          [sysname]        NOT NULL,
    [DatabaseLoginTypeDescription]               NVARCHAR (60)    NOT NULL,
    [DatabaseLoginAuthenticationTypeDescription] NVARCHAR (60)    NOT NULL,
    [DatabaseLoginDefaultSchemaName]             [sysname]        NULL,
    [ServerLoginName]                            [sysname]        NOT NULL,
    [ServerLoginTypeDescription]                 NVARCHAR (60)    NULL,
    [ServerLoginCreateDate]                      DATETIME         NULL,
    [ServerLoginModifyDate]                      DATETIME         NULL,
    [ServerLoginDefaultDatabaseName]             [sysname]        NULL,
    [DatabaseRoleId]                             INT              NOT NULL,
    [DatabaseRoleName]                           [sysname]        NOT NULL,
    [DatabaseRoleCreateDate]                     DATETIME         NULL,
    [DatabaseRoleModifyDate]                     DATETIME         NULL,
    [BuiltinDatabaseRole]                        BIT              NULL,
    [DatabasePermissionName]                     NVARCHAR (128)   NULL,
    [DatabasePermission]                         NVARCHAR (60)    NULL,
    [SchemaName]                                 NVARCHAR (128)   NULL,
    [SchemaPermissionName]                       NVARCHAR (128)   NULL,
    [SchemaPermission]                           NVARCHAR (60)    NULL,
    [DatabasePermissionCount]                    INT              NOT NULL,
    CONSTRAINT [PK_database_access_audit] PRIMARY KEY NONCLUSTERED ([DatabaseAccessAuditRecordId] ASC)
);

